config/routes.rb
Rails.application.routes.draw do
  get '/register', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  patch '/pitches', to: 'pitches#update_index'
  resources :users, except: :index
  resources :votes, only: [:create]
  resources :cohorts
  resources :pitches
  resources :rounds
  resources :admins

  root 'static#index', to: 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :users

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  belongs_to :round
  has_many :votes
  has_many :voters, through: :votes, class_name: "User"

  validates_presence_of :working_title, :description, :user_id, :round_id

  def sum_ranks
    # binding.pry
    votes = self.votes
    return votes.inject(0) { |sum, vote| sum += vote.ranking unless vote.ranking == nil }
  end

end

app/models/round.rb
class Round < ApplicationRecord
  has_many :votes
  has_many :pitches
  has_many :voters, through: :pitches, class_name: "User"

  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :votes
  has_many :pitches
  has_many :rounds, through: :pitches
  belongs_to :cohort

  validates_presence_of :name, :username, :email, :cohort
  validates_uniqueness_of :username, :email
  validates :username, length: {maximum: 30}
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :password, length: {minimum: 8, maximum: 30}
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voter, class_name: "User", foreign_key: :user_id
  belongs_to :pitch
  belongs_to :round

  validates_presence_of :user_id, :pitch_id, :round_id
  # validates_uniqueness_of :user_id, scope: [:pitch_id, :round_id]
  # validates_uniqueness_of :ranking, scope: [:user_id, :pitch_id, :round_id]
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :logged_in_user, :authorize

  def show
    @pitches = Pitch.all.sort_by { |pitch| pitch.votes.count }.reverse
    @cohorts = Cohort.all
    @round = current_user.rounds
    # binding.pry
    render :show
  end

  private

    def set_admin
      @admin = User.find_by(id: params[:id])
    end

    def authorize
      render 'error_404' unless current_user.admin?
    end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController

  def index
  end

  def new
  end

  def create
    # create pitch and add to list of pitches with ajax
    # currently incomplete
    @pitch = Pitch.new(pitch_params)
    if @pitch.save
      if request.xhr?
        # return pitch partial
      end
      # redirect
    else
      user = @pitch.user
      @errors = pitch.errors.full_messages
      render user
    end
  end

  def edit
  end

  def update_index
    # binding.pry
    @cohorts = Cohort.all
    @pitches = Pitch.where(selected: false)
    if params[:commit] == "Select Final Pitches"
      # redirect to final round
    elsif params[:commit] == "Select Top Pitches"
      @round = Round.new(name: "second", can_vote: true)
      if @round.save
        # something
        @second_round_pitches = Pitch.where(selected: true)
        @second_round_pitches.each do |pitch|
          pitch.update_attributes(round_id: @round.id, selected: false)
        end
        # binding.pry
        render 'admins/show'
      else
        @errors = @round.errors.full_messages
        render current_user
      end
    else
      pitch = Pitch.find_by(id: params[:pitch_id])
      if pitch.update_attributes(selected: true)
        flash[:succes] = "Pitch Selected"
        redirect_to current_user
      else
        @errors = current_user.errors.full_messages
      end
    end
  end

  def update
  end

  def destroy
  end

  private
    def pitch_params
      params.require(:pitch).permit(:working_title, :description)
    end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def new
  end

  def create
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :find_and_ensure_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def new
    @cohorts = Cohort.order(:name)
  end

  def create
    @cohorts = Cohort.order(:name)
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Thank you for creating an account!'
      protected(user)
    else
      @errors = user.errors.full_messages
      render 'new'
    end
  end

  def show
    if current_user.admin
      redirect_to admin_path(current_user)
    else
      @first_round = Round.where(name: "first")[0]
      @second_round = Round.where(name: "second")[0]
      @final_round = Round.where(name: "final")[0]
      # binding.pry
      @first_round_pitches = Pitch.where(round_id: @first_round.id)
      @second_round_pitches = Pitch.where(round_id: @second_round.id) if @second_round
      @final_pitches = Pitch.where(round_id: @final_round.id) if @final_round

      @pitches = []
      Pitch.all.each do |pitch|
        @pitches << pitch if pitch.user.cohort == @user.cohort
      end

      render 'show_student'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :cohort_id, :password, :password_confirmation)
    end

    def find_and_ensure_user
      @user = User.find_by(id: params[:id]) #if set to session[:user_id] then this will always evaluate to true for correct_user?
    end

    def correct_user
      redirect_to root_url unless current_user?
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    @vote = Vote.new
  end

  def create
    # binding.pry
    if params["commit"] == "Final Vote Rankings"
      @vote = Vote.new(vote_ranking_params)
      if @vote.save
        flash[:notice] = "thank you for submitting your rankings"
      else
        flash[:danger] = "rankings not saved"
      end
    else
      @vote = Vote.new(vote_params)
      if @vote.save
        flash[:notice] = "thank you for voting"
      else
        flash.now[:danger] = "vote did not save"
      end
    end
  end

  private
    def vote_params
      # binding.pry
      params.require(:vote).permit(:user_id, :pitch_id, :round_id)
    end

    def vote_ranking_params
      params.require(:vote).permit(:user_id, :pitch_id, :round_id, :ranking)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pitch_helper.rb
module PitchHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/round_helper.rb
module RoundHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?
    find_and_ensure_user
    @user == current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def admin?
    !!current_user.admin
  end

  def protected(user)
    redirect_to user_path(user) unless user.admin? #probably current_user
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in'
      redirect_to signin_url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:forarding_url] || default)
    session.delete(:forarding_url)
  end

  def store_location
    session[:forarding_url] = request.original_url if request.get?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/admins/_cohort_form.html.erb
<%= form_for :cohort, url: cohorts_path do |f| %>
    <%= render partial: 'application/errors', layout: false, locals: { errors: @errors } %>

      <p class="cohort-fields-container">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>


  <div class="actions">
    <button id="create-cohort-btn" class="pure-button pure-button-primary create-cohort-btn">Create Cohort</button>
  </div>
<% end %>

app/views/admins/show.html.erb
<section class="container">
  <section id="create-cohort">
    <p id="cohort-box-title">Create a New Cohort</p>
    <%= render partial: 'admins/cohort_form', layout: false, locals: {user: @user} %>
  </section>
  <section id="Cohorts">
    <h3>Cohorts</h3>
    <ul>
    <% @cohorts.each do |cohort| %>
      <li><%= cohort.name %></li>
    <% end %>
    </ul>
  </section>
  <% if @round.name == "second" %>
    <section class="pitch-container">
      <h3>Second Round Pitches</h3>
      <div class="pitch-content">
        <%= form_for :pitch, :url => { :controller => "pitches", :action => "update_index" }, :html => { :method => :patch } do |f| %>
          <table>
            <tr>
              <td>Working Title</td>
              <td>Description</td>
              <td>Select Pitch</td>
            <tr>
            <% @second_round_pitches.each do |pitch| %>
              <tr>
                <td><%= pitch.working_title %></td>
                <td><%= pitch.description %></td>
                <td><%= pitch.user.name %></td>
                <td><%= pitch.sum_ranks %></td>
                <% unless @round.name == "final" %>
                  <td>
                    <% unless pitch.selected %>
                      <button type="submit" name="pitch_id" value=<%= pitch.id %> class="fa fa-sort-desc vote-button upvote-button"></button>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </table>
          <div class="actions btn btn-lg">
            <%= f.submit "Select Final Pitches" %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>
  <section class="pitch-container">
    <h3>First Round Pitches</h3>
    <div class="pitch-content">
      <%= form_for :pitch, :url => { :controller => "pitches", :action => "update_index" }, :html => { :method => :patch } do |f| %>
        <table>
          <tr>
            <td>Working Title</td>
            <td>Description</td>
            <td>Select Pitch</td>
          <tr>
          <% @pitches.each do |pitch| %>
            <tr>
              <td><%= pitch.working_title %></td>
              <td><%= pitch.description %></td>
              <td><%= pitch.user.name %></td>
              <td><%= pitch.votes.count %></td>
              <% unless @round.name == "second" || @round.name == "final" %>
                <td>
                  <% unless pitch.selected %>
                    <button type="submit" name="pitch_id" value=<%= pitch.id %> class="fa fa-sort-desc vote-button upvote-button"></button>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </table>
        <% unless @round.name == "second" || @round.name == "final" %>
          <div class="actions btn btn-lg">
            <%= f.submit "Select Top Pitches" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbcProjectVoter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading main-heading" href="/">VoteForMe</a>

        <ul class="pure-menu-list">
            <% if logged_in? %>
            <li class="pure-menu-item"><%= link_to 'My Account', current_user, class: 'pure-menu-link' %></li>
            <li class="pure-menu-item"><%= link_to 'Sign Out', signout_path, method: 'delete', class: 'pure-menu-link' %></li>
            <% else %>
            <li class="pure-menu-item"><%= link_to 'Register', register_path, class: 'pure-menu-link' %></li>
            <li class="pure-menu-item"><%= link_to 'Sign In', signin_path, class: 'pure-menu-link' %></li>
            <% end %>
        </ul>
    </div>
    </div>
    <div class="notice"><%= flash[:success] %></div>
    <div class="alert"><%= flash[:danger] %></div>

    <div class="splash-container">
    <div class="splash">
        <div class="splash-head">
          <h1 class="splash-title"></h1>
          <%= yield %>
        </div>

        <p class="splash-subhead">
          VoteForMe, a web-app designed to streamline the voting process for final projects for Phase 3 students at Dev Bootcamp. A UI built for ease of use and navigation, eliminating the excuse of not voting or pitching an idea.
          <a href="/register">Register</a> and give us a try.</p>
        <% if !logged_in? %>
        <p>
            <a href="/register" class="idx-btn pure-button pure-button-primary">Register</a>
            <a href="/signin" class="idx-btn pure-button pure-button-primary">Sign In</a>
        </p>
      <% end %>
    </div>
    </div>
    <div class="footer l-box is-center">
        ©VoteForMeDBC 2016
    </div>

  </body>
</html>