config/routes.rb
Rails.application.routes.draw do
  get '/register', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  patch '/pitches', to: 'pitches#update_index'
  resources :users, except: :index
  resources :votes, only: [:create]
  resources :cohorts
  resources :pitches
  resources :rounds
  resources :admins

  root 'static#index', to: 'static#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :votes
  has_many :pitches
  has_many :rounds, through: :pitches
  belongs_to :cohort

  validates_presence_of :name, :username, :email, :cohort
  validates_uniqueness_of :username, :email
  validates :username, length: {maximum: 30}
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :password, length: {minimum: 8, maximum: 30}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, :find_and_ensure_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def new
    @cohorts = Cohort.order(:name)
  end

  def create
    @cohorts = Cohort.order(:name)
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Thank you for creating an account!'
      protected(user)
    else
      @errors = user.errors.full_messages
      render 'new'
    end
  end

  def show
    if current_user.admin
      redirect_to admin_path(current_user)
    else
      @first_round = Round.where(name: "first")[0]
      @second_round = Round.where(name: "second")[0]
      @final_round = Round.where(name: "final")[0]
      # binding.pry
      @first_round_pitches = Pitch.where(round_id: @first_round.id)
      @second_round_pitches = Pitch.where(round_id: @second_round.id) if @second_round
      @final_pitches = Pitch.where(round_id: @final_round.id) if @final_round

      @pitches = []
      Pitch.all.each do |pitch|
        @pitches << pitch if pitch.user.cohort == @user.cohort
      end

      render 'show_student'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :cohort_id, :password, :password_confirmation)
    end

    def find_and_ensure_user
      @user = User.find_by(id: params[:id]) #if set to session[:user_id] then this will always evaluate to true for correct_user?
    end

    def correct_user
      redirect_to root_url unless current_user?
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register New Account</h1>

<%= form_for :user, url: users_path do |f| %>
  <%= render partial: 'application/errors', layout: false, locals: { errors: @errors } %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p class="pure-u-1 pure-u-md-1-3">
    <%= f.label :cohort %>
    <select id="user_cohort_id" name="user[cohort_id]" class="pure-input-1-2">
      <% @cohorts.each do |cohort| %>
      <option value="<%= cohort.id %>"><%= cohort.name %></option>
      <% end %>
    </select>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <button id="sign_up_btn" class="pure-button pure-button-primary sign-up">Create Account</button>
  </p>
<% end %>

app/views/users/show_student.html.erb
<div class="container">

  <div class="sidebar">
    <% if !@second_round && !@final_round %>
      <% if @user.pitches.count < 4 %>
        <h2>Add a Pitch!</h2>
        <!-- form for adding a new pitch - currently does not work - this will work with AJAX -->
        <%= form_for :pitch, url: pitches_path, :html => { class: "pure-form pure-form-aligned new-pitch-form" } do |f| %>
        <fieldset>
          <label for="title">Title:</label>
          <%= f.text_field :working_title %>
          <label for="description">Description:</label>
          <%= f.text_area :description %>
          <button id="add-pitch-btn" class="pure-button pure-button-primary sign-up">Add Pitch</button>
        </fieldset>
        <% end %>
      <% elsif @user.pitches.count >= 4 %>
        <h2>Thanks! You've already submitted four pitches.  Let the voting commence!</h2>
      <% end %>
    <% end %>
  </div>
  <% if @final_pitches %>
    <div class="main"
      <div class="final-projects">
        <h2>Final Projects!</h2>
        <ul class="final-pitches">
          <% @final_pitches.each do |pitch| %>
            <% if pitch.round.name == "final" %>
              <li class="pitch">
                <%=  pitch.working_title %> - <%= pitch.description %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if @second_round_pitches %>
    <div class="round-2-voting">
      <h2>Round 2 Voting:</h2>
      <table class="round-2-pitches">
        <tr class="pitch-table-row-header">
        <td class="column-header">Working Title</td>
        <td class="column-header">Description</td>
        </tr>
        <%= form_for :pitch, url: votes_path, :html => { method: "POST", class: "pure-form pure-form-aligned new-pitch-form" } do |f| %>
          <% @second_round_pitches.each do |pitch| %>
            <tr class="pitch">
              <td><%=  pitch.working_title %></td><td><%= pitch.description %></td>
              <td>
                <%= f.select(:rankings, options_for_select([[5], [4], [3], [2], [1]]), {}, {class: "rankings form-control"}) %>
              </td>
          <% end %>
        </tr>
      </table>
      <div class="actions btn btn-lg">
        <button class="final-vote-btn pure-button pure-button-primary sign-up">Submit Final Round Rankings</button>
      </div>
      <% end %>
    </div>
  <% end %>

  <% if @first_round_pitches %>
    <div class="round-1-voting">
      <h2>Round 1 Voting:</h2>
      <table class="round-1-pitches">
        <tr class="pitch-table-row-header">
          <td class="column-header">Working Title</td>
          <td class="column-header">Description</td>
          <% if @first_round.can_vote && !@second_round %>
            <td class="column header vote-header">Vote for Pitch</td>
          <% end %>
        </tr>
        <% @first_round_pitches.each do |pitch| %>
          <% if pitch.round.name == "first" %>
            <tr>
              <td><%=  pitch.working_title %></td>
              <td><%= pitch.description %></td>
              <% if @first_round.can_vote && !@second_round %>
                <td class="vote-btn-table-row">
                  <!-- vote button for round 1 - currently doesn't work -->
                  <form class="vote-btn" method="post" action="/votes">
                    <button class="button-xsmall vote-btn pure-button pure-button-primary sign-up">Vote</button>
                  </form>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  <% end %>

</div>